# Generated by Django 2.0.4 on 2018-06-17 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleparticipator',
            name='participator',
            field=models.ForeignKey(help_text='the user who participate the schedule.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='participator'),
        ),
        migrations.AddField(
            model_name='scheduleparticipator',
            name='schedule',
            field=models.ForeignKey(help_text='the schedule that user participate.', on_delete=django.db.models.deletion.CASCADE, to='Schedule.Schedule', verbose_name='schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='creator',
            field=models.ForeignKey(help_text="schedule's creator.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.ForeignKey(help_text="the schedule's type.", on_delete=django.db.models.deletion.CASCADE, to='Schedule.ScheduleType', verbose_name='type'),
        ),
    ]
