# Generated by Django 2.0.5 on 2018-06-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text="user's nick name, can be not fill in form.", max_length=32, verbose_name='username')),
                ('password', models.CharField(blank=True, help_text='password', max_length=32, verbose_name='password')),
                ('date_last_logged_in', models.DateTimeField(help_text="user's last login time, use timezone.now() to fill it.", null=True, verbose_name='date_last_logged_in')),
                ('schedule_created_count', models.IntegerField(default=0, help_text='the number of schedule that user created, can only be modified by business layer, NOT use store procedure!', verbose_name='schedule_created_count')),
                ('schedule_attended_count', models.IntegerField(default=0, help_text='the number of schedule that user attended, exclude user created, can only be modified by business layer, NOT use store procedure!', verbose_name='schedule_attended_count')),
                ('notice_count', models.IntegerField(default=0, help_text='the number of notice that user created, can only be modified by business layer, NOT use store procedure!', verbose_name='notice_count')),
                ('gender', models.BooleanField(default=True, help_text="user's gender, True is Male, False is Female, default is True.", verbose_name='gender')),
                ('birthday', models.DateField(help_text="user's birthday, must be YYYY-MM-DD", null=True, verbose_name='birthday')),
            ],
        ),
    ]
